<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[3]=array(0,1,1,'6Kej5Yaz5pa55qGI');
$cfg_Cs[4]=array(0,1,1,'5LiT5Yip5Y+K5qOA5rWL5oql5ZGK');
$cfg_Cs[5]=array(0,1,1,'5Yqg55uf5ZCI5L2c');
$cfg_Cs[6]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[7]=array(0,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[24]=array(0,1,1,'5bel56iL5qGI5L6L');
$cfg_Cs[25]=array(0,1,1,'5Lqn5ZOB54m554K5');
$cfg_Cs[9]=array(6,1,1,'IOiGnOazleWvjOawp+aWsOmjjuezu+e7nw==');
$cfg_Cs[10]=array(6,1,1,'IOiGnOazleWvjOawp+aWsOmjjuezu+e7nw==');
$cfg_Cs[11]=array(6,1,1,'IOiGnOazleWvjOawp+aWsOmjjuezu+e7nw==');
?>