<?php
$z[0]=Array("typeurl","",13,29);
$z[1]=Array("global","",41,74);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typename","",130,147);
$z[3]=Array("typeurl","",170,186);
$z[4]=Array("global","",198,231);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",358,391);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("content","",585,627);
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("global","",660,686);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("typeurl","",756,772);

?>