<?php
$z[0]=Array("typeurl","",13,29);
$z[1]=Array("global","",41,74);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typename","",130,147);
$z[3]=Array("typeurl","",170,186);
$z[4]=Array("global","",198,231);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",358,391);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",499,525);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("typeurl","",595,611);

?>