<?php
$z[0]=Array("global","",32,57);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","<span>|</span><a href=\"[field:typeurl/]\">[field:typename/]</a>",76,178);
$z[1][4]['type']="top";
$z[2]=Array("global","",511,535);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",1247,1279);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1384,1416);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1656,1688);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1891,1923);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",2134,2166);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",2464,2496);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",2667,2699);
$z[9][4]['name']="cfg_templets_skin";

?>