<?php
$z[0]=Array("global","",33,58);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","<span>|</span><a href=\"[field:typeurl/]\">[field:typename/]</a>",77,179);
$z[1][4]['type']="top";
$z[2]=Array("global","",285,309);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",491,518);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",530,562);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",616,642);
$z[5][4]['name']="cfg_webname";

?>