<?php
$z[0]=Array("global","",32,57);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","<span>|</span><a href=\"[field:typeurl/]\">[field:typename/]</a>",76,178);
$z[1][4]['type']="top";
$z[2]=Array("global","",511,535);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",1264,1296);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1401,1433);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1673,1705);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1908,1940);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",2151,2183);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",2481,2513);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",2684,2716);
$z[9][4]['name']="cfg_templets_skin";

?>