<?php
$z[0]=Array("global","",29,56);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",94,126);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",149,175);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",301,326);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",360,485);
$z[4][4]['type']="top";
$z[4][4]['row']="8";
$z[5]=Array("global","",573,605);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",655,681);
$z[6][4]['name']="cfg_webname";

?>