<?php
$z[0]=Array("global","",29,56);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",68,100);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",123,149);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",275,300);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",334,459);
$z[4][4]['type']="top";
$z[4][4]['row']="8";
$z[5]=Array("global","",547,579);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",629,655);
$z[6][4]['name']="cfg_webname";

?>