<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",324,354);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",391,418);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",469,501);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",539,574);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",678,710);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",931,963);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1202,1234);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1518,1550);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("type","\r\n        	<h2><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_c_tit.png\" width=\"176\" height=\"36\" alt=\"[field:typename/]\" /></a><span><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_more.png\" width=\"28\" height=\"16\" alt=\"更多\" /></a></span></h2>",1784,2140);
$z[9][4]['typeid']="6";
$z[10]=Array("arclist","\r\n            	<li><a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" width=\"200\" height=\"150\" alt=\"[field:title/]\" /></a><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n			",2163,2401);
$z[10][4]['typeid']="6";
$z[10][4]['row']="4";
$z[11]=Array("type","\r\n        	<h2><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_l_tit.png\" width=\"130\" height=\"36\" alt=\"[field:typename/]\" /></a><span><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_more.png\" width=\"28\" height=\"16\" alt=\"更多\" /></a></span></h2>\r\n            <dl>\r\n            	<dt><img src=\"[field:global.cfg_templets_skin/]/images/about.jpg\" width=\"200\" height=\"150\" alt=\"关于我们\" /></dt>\r\n                <dd><p><script src='[field:global.cfg_cmsurl/]/plus/mytag_js.php?aid=1' language='javascript'></script>... <a href=\"[field:typeurl/]\">详细内容>></a></p></dd>\r\n            </dl>\r\n		",2508,3216);
$z[11][4]['typeid']="7";
$z[12]=Array("type","\r\n        	<h2><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_r_tit.png\" width=\"142\" height=\"36\" alt=\"[field:typename/]\" /></a><span><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_more.png\" width=\"28\" height=\"16\" alt=\"更多\" /></a></span></h2>",3273,3629);
$z[12][4]['typeid']="7";
$z[13]=Array("global","",3659,3684);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("include","",3789,3826);
$z[14][4]['filename']="footer.htm";

?>