<?php
$z[0]=Array("global","",250,276);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",319,349);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",385,412);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",462,494);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",528,563);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",637,669);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",818,850);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",986,1018);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1154,1186);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("type","\n        	<h2><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_c_tit.png\" width=\"176\" height=\"36\" alt=\"[field:typename/]\" /></a><span><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_more.png\" width=\"28\" height=\"16\" alt=\"更多\" /></a></span></h2>",1364,1719);
$z[9][4]['typeid']="6";
$z[10]=Array("arclist","\n            	<li><a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" width=\"200\" height=\"150\" alt=\"[field:title/]\" /></a><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n			",1740,2004);
$z[10][4]['typeid']="6";
$z[10][4]['row']="4";
$z[10][4]['orderby']="id";
$z[10][4]['orderway']="asc";
$z[11]=Array("type","\n        	<h2><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_g_tit.png\" width=\"176\" height=\"36\" alt=\"[field:typename/]\" /></a><span><a href=\"[field:typeurl/]\"><img src=\"[field:global.cfg_templets_skin/]/images/con_bot_more.png\" width=\"28\" height=\"16\" alt=\"更多\" /></a></span></h2>",2136,2492);
$z[11][4]['typeid']="24";
$z[12]=Array("arclist","\n            	<li><a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" width=\"200\" height=\"150\" alt=\"[field:title/]\" /></a><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n			",2513,2750);
$z[12][4]['typeid']="24";
$z[12][4]['row']="4";
$z[13]=Array("include","",2839,2876);
$z[13][4]['filename']="footer.htm";

?>