<?php
$z[0]=Array("type","[field:typename/]",34,85);
$z[0][4]['typeid']="6";
$z[1]=Array("channel","\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n      ",133,246);
$z[1][4]['typeid']="6";
$z[2]=Array("arclist","\n		<li>				\n		<a href=\"[field:arcurl/]\">[field:title/]</a></li>\n	",296,409);
$z[2][4]['typeid']="6";
$z[2][4]['row']="4";
$z[3]=Array("global","",538,563);
$z[3][4]['name']="cfg_cmsurl";

?>